# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

##github: [metadata]
##  encoding: UTF-8
## kramdown:
##   input: GFM
##   hard_wrap: false
## future: true
## jailed: false
## theme: jekyll-theme-primer
## gfm_quirks: paragraph_end

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ja
title: 脱出日記
author: プレハブ小屋
email: yojyo@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  安住の地が見つかるまで東京都内を徘徊する者による日記。
baseurl: /wandering # the subpath of your site, e.g. /blog
url: https://showa-yojyo.github.io
repository: https://github.com/showa-yojyo/wandering

header_pages:
  - about.md
  - diary.md
  - libraries.md

twitter_username: showa_yojyo
github_username:  showa-yojyo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - Gemfile
  - Gemfile.lock
  - tools/

# Minima settings
minima:
  date_format: "%Y-%m-%d (%a)"

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      author: showa-yojyo
      categories: diary
      layout: diary
  - scope:
       path: _libraries
       type: libraries
    values:
      layout: library

collections:
  libraries:
    output: true

paginate: 5
paginate_path: "page:num"
